"""AutoTree Python SDK public API."""

from .client import TreeClient
from .errors import (
    AutoTreeError,
    ExportError,
    SSEParseError,
    TraceInvariantError,
    TreeHTTPError,
    TreeNotSupportedError,
    TreeStreamError,
)
from .models import (
    BranchStats,
    BranchMergedEvent,
    BranchPrunedEvent,
    BranchStartedEvent,
    ChatCompletionResponse,
    DoneEvent,
    EngineCounters,
    ErrorEvent,
    RolloutBatch,
    RolloutBranch,
    RolloutTree,
    StreamErrorDetails,
    TokenEvent,
    TreeCompletion,
    TreeCompletionResponse,
    TreeParameters,
    TreeSummary,
    Usage,
)
from .rollout import rollout
from .trace import TraceAssembler

__all__ = [
    "AutoTreeError",
    "BranchStats",
    "BranchMergedEvent",
    "BranchPrunedEvent",
    "BranchStartedEvent",
    "ChatCompletionResponse",
    "DoneEvent",
    "EngineCounters",
    "ErrorEvent",
    "ExportError",
    "RolloutBatch",
    "RolloutBranch",
    "RolloutTree",
    "SSEParseError",
    "StreamErrorDetails",
    "TokenEvent",
    "TraceAssembler",
    "TraceInvariantError",
    "TreeClient",
    "TreeCompletion",
    "TreeCompletionResponse",
    "TreeHTTPError",
    "TreeNotSupportedError",
    "TreeParameters",
    "TreeStreamError",
    "TreeSummary",
    "Usage",
    "rollout",
]
