#!/usr/bin/env python3
"""Render and verify the checked-in plain Kubernetes manifest."""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CHART = ROOT / "deploy" / "helm" / "autotree"
OUTPUT = ROOT / "deploy" / "k8s" / "autotree.yaml"
HEADER = "# Generated by deploy/render.py; edit the Helm chart, not this file.\n"


def helm_binary() -> str:
    configured = os.environ.get("HELM")
    candidates = [
        configured,
        str(ROOT / "deploy" / "tools" / "helm.exe"),
        str(ROOT / "deploy" / "tools" / "helm"),
        shutil.which("helm"),
    ]
    for candidate in candidates:
        if candidate and Path(candidate).is_file():
            return candidate
    raise SystemExit(
        "helm was not found; set HELM or place the portable binary in deploy/tools/"
    )


def render() -> str:
    command = [
        helm_binary(),
        "template",
        "autotree",
        str(CHART),
        "--namespace",
        "autotree",
    ]
    result = subprocess.run(
        command,
        check=True,
        cwd=ROOT,
        text=True,
        stdout=subprocess.PIPE,
    )
    return HEADER + result.stdout.replace("\r\n", "\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("mode", choices=("render", "check"), nargs="?", default="render")
    args = parser.parse_args()
    rendered = render()
    if args.mode == "render":
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(rendered, encoding="utf-8", newline="\n")
        print(f"rendered {OUTPUT.relative_to(ROOT)}")
        return 0
    if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
        print(
            f"{OUTPUT.relative_to(ROOT)} is stale; run: python deploy/render.py render",
            file=sys.stderr,
        )
        return 1
    print(f"checked {OUTPUT.relative_to(ROOT)}: in sync")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
